version: '3.8'

services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  wiremock:
    image: 'wiremock/wiremock:latest'
    container_name: wiremock
    ports:
      - '8080:8080'
    volumes:
      - './wiremock/mappings:/home/wiremock/mappings'
      - './wiremock/__files:/home/wiremock/__files'
    networks:
      - backend
    environment:
      - HTTP_PORT=8080
    restart: always

networks:
  backend:
    driver: bridge